server:
    port: 1206

mybatis:
    type-aliases-package: com.fengshang.im.bean              # 所有Entity别名类所在包
    mapper-locations: classpath:mapper/*Mapper.xml      # mapper映射文件 - classpath:mybatis/mapper/**/*.xml
    configuration:
        map-underscore-to-camel-case: true

spring:
    data:
        mongodb:
            host: 127.0.0.1
            database: FSIM
            port: 27017
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/FSIM?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
        username: //mysql用户名
        password: //mysql密码
        druid:
            min-idle: 5                                 # 数据库连接池最小维持连接数
            initial-size: 5                            # 初始连接数
            max-total: 10                               # 最大连接数
            max-wait-millis: 2000                      # 等待链接获取的最大超时时间
